name: oneApi-windows
description: Install Intel oneAPI
inputs:
  WINDOWS_HPCKIT_URL: 
    description: 'URL to download the Intel oneAPI HPC Toolkit for Windows'
    default: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f07e32fa-b505-4b90-8a79-e328ce9ad9d6/intel-oneapi-hpc-toolkit-2025.0.0.822_offline.exe
    required: false
  WINDOWS_COMPONENTS: # If more than one component required then separate them with : (colon)
    description: 'Components to install for Intel oneAPI C++ compiler for Windows'
    default: intel.oneapi.win.cpp-dpcpp-common
    required: false

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      clean: false
  - name: Check cache for Intel oneAPI
    id: cache-install
    uses: actions/cache@v4
    with:
      path: |
          C:\Program Files (x86)\Intel
      key: install-${{ inputs.WINDOWS_HPCKIT_URL }}-${{ inputs.WINDOWS_COMPONENTS }}-compiler-${{ hashFiles('${{ github.action_path }}/action.yml') }}
  
  - name: Install Intel oneAPI
    if: steps.cache-install.outputs.cache-hit != 'true'
    run: |
      installOneApi.bat ${{ inputs.WINDOWS_HPCKIT_URL }}  ${{ inputs.WINDOWS_COMPONENTS }}
    working-directory: ${{ github.action_path }}/scripts
    shell: cmd

  - name: Set up variables
    run: |
      updateEnvironment.bat
    shell: cmd
    working-directory: ${{ github.action_path }}/scripts