@echo off
rem Generated by Copilot (mostly..)

rem Store the environment variables before
setlocal EnableDelayedExpansion
for /f "tokens=1* delims==" %%a in ('set') do (
    @set "before_%%a=%%b"
)

rem Call the Intel setvars.bat
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"

rem Compare and print the differences, excluding variables starting with "before_"
for /f "tokens=1* delims==" %%a in ('set') do (
    @set "var=%%a"
    if "!var:~0,7!" neq "before_" (
        if "!%%a!" neq "!before_%%a!" (
            echo %%a=!%%a! >> "%GITHUB_ENV%"
        )
    )
)
endlocal